//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `numbers-ZerocIce.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package NumbersApp;

public class RangeError extends com.zeroc.Ice.UserException
{
    public RangeError()
    {
        this.reason = "";
    }

    public RangeError(Throwable cause)
    {
        super(cause);
        this.reason = "";
    }

    public RangeError(String reason)
    {
        this.reason = reason;
    }

    public RangeError(String reason, Throwable cause)
    {
        super(cause);
        this.reason = reason;
    }

    public String ice_id()
    {
        return "::NumbersApp::RangeError";
    }

    public String reason;

    /** @hidden */
    @Override
    protected void _writeImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice("::NumbersApp::RangeError", -1, true);
        ostr_.writeString(reason);
        ostr_.endSlice();
    }

    /** @hidden */
    @Override
    protected void _readImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        reason = istr_.readString();
        istr_.endSlice();
    }

    /** @hidden */
    public static final long serialVersionUID = 1476781246L;
}
